[project]
name = "elevenlabs-internals"
version = "0.1.0"
description = "ElevenLabs TTS internals"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.32.5",
    "soundfile>=0.13.1",
]


